# Generated by Django 5.2.8 on 2025-11-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='code_snippet',
            field=models.TextField(blank=True, help_text='Code context for the question', null=True),
        ),
    ]
